//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Активности
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Активности()
        {
            this.Пользователи = new HashSet<Пользователи>();
        }
    
        public int КодАктивности { get; set; }
        public Nullable<int> КодМероприятия { get; set; }
        public string Победители { get; set; }
        public string НазваниеАтивности { get; set; }
        public Nullable<int> День { get; set; }
        public Nullable<System.TimeSpan> ВремяНачала { get; set; }
    
        public virtual Мероприятия Мероприятия { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пользователи> Пользователи { get; set; }
    }
}
