//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vkysgovyadini
{
    using System;
    using System.Collections.Generic;
    
    public partial class Активности
    {
        public int КодАктивности { get; set; }
        public Nullable<int> КодМероприятия { get; set; }
        public string Победители { get; set; }
        public string НазваниеАктивности { get; set; }
        public Nullable<int> День { get; set; }
        public Nullable<System.TimeSpan> ВремяНачала { get; set; }
    
        public virtual Мероприятия Мероприятия { get; set; }
    }
}
