//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vkysgovyadini
{
    using System;
    using System.Collections.Generic;
    
    public partial class Мероприятия
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Мероприятия()
        {
            this.Активности = new HashSet<Активности>();
        }
    
        public int КодМероприятия { get; set; }
        public Nullable<int> КодГорода { get; set; }
        public string События { get; set; }
        public Nullable<System.DateTime> ДатаНачала { get; set; }
        public string Продолжительность { get; set; }
        public Nullable<int> КодНаправления { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Активности> Активности { get; set; }
        public virtual Города Города { get; set; }
        public virtual Направление Направление { get; set; }
    }
}
